### ISSUE TITLE
Printing colored strings within Terms

### ISSUE THREAD

**Issue by jvf** [project-fifo/cf#3]
Printing a coloured string as part of a term does not work, `~p` seems to escapes the color codes.

Example:

```
> io:format("~p~n", [{a,b,cf:format("~!rfoo~!!")}]).
{a,b,"\e[0;31mfoo\e[0m\e[0m"}
```

Any idea on how to get this to work?

**Comment by Licenser** [comment]
`~p` indicates that it should print a term not a string so erlang will convert control chars (like color codes) to their 'readable' representation. You got to do a bit of extra work here either:

```
> io:format("{~p, ~p, ~s}~n", [a,b,cf:format("~!rfoo~!!")]).
%% or
> cf:print("{~p, ~p, ~!rfoo~!!}~n", [a,b]).
```

using `~p` and nesting colors won't work as it is meant to exactly not do that :) (print control characters)
